# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.conf_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_groupBox.sizePolicy().hasHeightForWidth())
        self.conf_groupBox.setSizePolicy(sizePolicy)
        self.conf_groupBox.setObjectName("conf_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.conf_groupBox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.conf_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.antiAliasStage_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antiAliasStage_checkBox.sizePolicy().hasHeightForWidth())
        self.antiAliasStage_checkBox.setSizePolicy(sizePolicy)
        self.antiAliasStage_checkBox.setObjectName("antiAliasStage_checkBox")
        self.gridLayout_3.addWidget(self.antiAliasStage_checkBox, 1, 0, 1, 1)
        self.sampleHoldStage_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleHoldStage_checkBox.sizePolicy().hasHeightForWidth())
        self.sampleHoldStage_checkBox.setSizePolicy(sizePolicy)
        self.sampleHoldStage_checkBox.setObjectName("sampleHoldStage_checkBox")
        self.gridLayout_3.addWidget(self.sampleHoldStage_checkBox, 2, 0, 1, 1)
        self.recovFilterStage_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recovFilterStage_checkBox.sizePolicy().hasHeightForWidth())
        self.recovFilterStage_checkBox.setSizePolicy(sizePolicy)
        self.recovFilterStage_checkBox.setObjectName("recovFilterStage_checkBox")
        self.gridLayout_3.addWidget(self.recovFilterStage_checkBox, 4, 0, 1, 1)
        self.analogSwitchStage_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analogSwitchStage_checkBox.sizePolicy().hasHeightForWidth())
        self.analogSwitchStage_checkBox.setSizePolicy(sizePolicy)
        self.analogSwitchStage_checkBox.setObjectName("analogSwitchStage_checkBox")
        self.gridLayout_3.addWidget(self.analogSwitchStage_checkBox, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.conf_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.antiAliasOut_t_checkBox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antiAliasOut_t_checkBox.sizePolicy().hasHeightForWidth())
        self.antiAliasOut_t_checkBox.setSizePolicy(sizePolicy)
        self.antiAliasOut_t_checkBox.setObjectName("antiAliasOut_t_checkBox")
        self.gridLayout_10.addWidget(self.antiAliasOut_t_checkBox, 1, 0, 1, 1)
        self.sampleHoldOut_t_checkBox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleHoldOut_t_checkBox.sizePolicy().hasHeightForWidth())
        self.sampleHoldOut_t_checkBox.setSizePolicy(sizePolicy)
        self.sampleHoldOut_t_checkBox.setObjectName("sampleHoldOut_t_checkBox")
        self.gridLayout_10.addWidget(self.sampleHoldOut_t_checkBox, 2, 0, 1, 1)
        self.analogSwitchOut_t_checkBox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analogSwitchOut_t_checkBox.sizePolicy().hasHeightForWidth())
        self.analogSwitchOut_t_checkBox.setSizePolicy(sizePolicy)
        self.analogSwitchOut_t_checkBox.setObjectName("analogSwitchOut_t_checkBox")
        self.gridLayout_10.addWidget(self.analogSwitchOut_t_checkBox, 3, 0, 1, 1)
        self.inputSignalOut_t_checkBox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSignalOut_t_checkBox.sizePolicy().hasHeightForWidth())
        self.inputSignalOut_t_checkBox.setSizePolicy(sizePolicy)
        self.inputSignalOut_t_checkBox.setObjectName("inputSignalOut_t_checkBox")
        self.gridLayout_10.addWidget(self.inputSignalOut_t_checkBox, 0, 0, 1, 1)
        self.recovFilterOut_t_checkBox = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recovFilterOut_t_checkBox.sizePolicy().hasHeightForWidth())
        self.recovFilterOut_t_checkBox.setSizePolicy(sizePolicy)
        self.recovFilterOut_t_checkBox.setObjectName("recovFilterOut_t_checkBox")
        self.gridLayout_10.addWidget(self.recovFilterOut_t_checkBox, 4, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.antiAliasOut_f_checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antiAliasOut_f_checkBox.sizePolicy().hasHeightForWidth())
        self.antiAliasOut_f_checkBox.setSizePolicy(sizePolicy)
        self.antiAliasOut_f_checkBox.setObjectName("antiAliasOut_f_checkBox")
        self.gridLayout_11.addWidget(self.antiAliasOut_f_checkBox, 1, 0, 1, 1)
        self.sampleHoldOut_f_checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleHoldOut_f_checkBox.sizePolicy().hasHeightForWidth())
        self.sampleHoldOut_f_checkBox.setSizePolicy(sizePolicy)
        self.sampleHoldOut_f_checkBox.setObjectName("sampleHoldOut_f_checkBox")
        self.gridLayout_11.addWidget(self.sampleHoldOut_f_checkBox, 2, 0, 1, 1)
        self.analogSwitchOut_f_checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analogSwitchOut_f_checkBox.sizePolicy().hasHeightForWidth())
        self.analogSwitchOut_f_checkBox.setSizePolicy(sizePolicy)
        self.analogSwitchOut_f_checkBox.setObjectName("analogSwitchOut_f_checkBox")
        self.gridLayout_11.addWidget(self.analogSwitchOut_f_checkBox, 3, 0, 1, 1)
        self.inputSignalOut_f_checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSignalOut_f_checkBox.sizePolicy().hasHeightForWidth())
        self.inputSignalOut_f_checkBox.setSizePolicy(sizePolicy)
        self.inputSignalOut_f_checkBox.setObjectName("inputSignalOut_f_checkBox")
        self.gridLayout_11.addWidget(self.inputSignalOut_f_checkBox, 0, 0, 1, 1)
        self.recovFilterOut_f_checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recovFilterOut_f_checkBox.sizePolicy().hasHeightForWidth())
        self.recovFilterOut_f_checkBox.setSizePolicy(sizePolicy)
        self.recovFilterOut_f_checkBox.setObjectName("recovFilterOut_f_checkBox")
        self.gridLayout_11.addWidget(self.recovFilterOut_f_checkBox, 4, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.conf_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.sampleRat_spinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRat_spinBox.sizePolicy().hasHeightForWidth())
        self.sampleRat_spinBox.setSizePolicy(sizePolicy)
        self.sampleRat_spinBox.setDecimals(0)
        self.sampleRat_spinBox.setMinimum(1.0)
        self.sampleRat_spinBox.setMaximum(999999999999.0)
        self.sampleRat_spinBox.setObjectName("sampleRat_spinBox")
        self.gridLayout_7.addWidget(self.sampleRat_spinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.sampleCycle_spinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleCycle_spinBox.sizePolicy().hasHeightForWidth())
        self.sampleCycle_spinBox.setSizePolicy(sizePolicy)
        self.sampleCycle_spinBox.setMinimum(0.05)
        self.sampleCycle_spinBox.setMaximum(0.95)
        self.sampleCycle_spinBox.setSingleStep(0.05)
        self.sampleCycle_spinBox.setProperty("value", 0.5)
        self.sampleCycle_spinBox.setObjectName("sampleCycle_spinBox")
        self.gridLayout_7.addWidget(self.sampleCycle_spinBox, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.updateSampe_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.updateSampe_pushButton.setObjectName("updateSampe_pushButton")
        self.gridLayout_6.addWidget(self.updateSampe_pushButton, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.conf_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.squareWaveform_radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.squareWaveform_radioButton.sizePolicy().hasHeightForWidth())
        self.squareWaveform_radioButton.setSizePolicy(sizePolicy)
        self.squareWaveform_radioButton.setObjectName("squareWaveform_radioButton")
        self.gridLayout_17.addWidget(self.squareWaveform_radioButton, 2, 0, 1, 1)
        self.altSinWaveform_RadioButton = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSinWaveform_RadioButton.sizePolicy().hasHeightForWidth())
        self.altSinWaveform_RadioButton.setSizePolicy(sizePolicy)
        self.altSinWaveform_RadioButton.setObjectName("altSinWaveform_RadioButton")
        self.gridLayout_17.addWidget(self.altSinWaveform_RadioButton, 1, 0, 1, 1)
        self.sinWave_radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinWave_radioButton.sizePolicy().hasHeightForWidth())
        self.sinWave_radioButton.setSizePolicy(sizePolicy)
        self.sinWave_radioButton.setObjectName("sinWave_radioButton")
        self.gridLayout_17.addWidget(self.sinWave_radioButton, 0, 0, 1, 1)
        self.XcWaveform_radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.XcWaveform_radioButton.setObjectName("XcWaveform_radioButton")
        self.gridLayout_17.addWidget(self.XcWaveform_radioButton, 3, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_7, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 1, 0, 1, 1)
        self.inputSignalFreq_spinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSignalFreq_spinBox.sizePolicy().hasHeightForWidth())
        self.inputSignalFreq_spinBox.setSizePolicy(sizePolicy)
        self.inputSignalFreq_spinBox.setDecimals(0)
        self.inputSignalFreq_spinBox.setMinimum(1.0)
        self.inputSignalFreq_spinBox.setMaximum(999999999999.0)
        self.inputSignalFreq_spinBox.setSingleStep(1.0)
        self.inputSignalFreq_spinBox.setObjectName("inputSignalFreq_spinBox")
        self.gridLayout_15.addWidget(self.inputSignalFreq_spinBox, 1, 1, 1, 1)
        self.inputSignalAmp_spinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSignalAmp_spinBox.sizePolicy().hasHeightForWidth())
        self.inputSignalAmp_spinBox.setSizePolicy(sizePolicy)
        self.inputSignalAmp_spinBox.setObjectName("inputSignalAmp_spinBox")
        self.gridLayout_15.addWidget(self.inputSignalAmp_spinBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 2, 0, 1, 1)
        self.updateInput_pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.updateInput_pushButton.setObjectName("updateInput_pushButton")
        self.gridLayout_15.addWidget(self.updateInput_pushButton, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.exportPlots_pushButton = QtWidgets.QPushButton(self.conf_groupBox)
        self.exportPlots_pushButton.setObjectName("exportPlots_pushButton")
        self.verticalLayout_2.addWidget(self.exportPlots_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.mainGridLayout.addWidget(self.conf_groupBox, 0, 0, 2, 1)
        self.figureLayout = QtWidgets.QVBoxLayout()
        self.figureLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.figureLayout.setObjectName("figureLayout")
        self.mainGridLayout.addLayout(self.figureLayout, 0, 1, 2, 1)
        self.gridLayout_2.addLayout(self.mainGridLayout, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfig_AAF_Settings = QtWidgets.QAction(MainWindow)
        self.actionConfig_AAF_Settings.setObjectName("actionConfig_AAF_Settings")
        self.actionRecovery_Filter_Settings = QtWidgets.QAction(MainWindow)
        self.actionRecovery_Filter_Settings.setObjectName("actionRecovery_Filter_Settings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.conf_groupBox.setTitle(_translate("MainWindow", "Configuration"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Stage ON/OFF"))
        self.antiAliasStage_checkBox.setText(_translate("MainWindow", "Anti Aliasing Filter"))
        self.sampleHoldStage_checkBox.setText(_translate("MainWindow", "Sample && Hold"))
        self.recovFilterStage_checkBox.setText(_translate("MainWindow", "Recovery Filter"))
        self.analogSwitchStage_checkBox.setText(_translate("MainWindow", "Analog Switch"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output Node"))
        self.groupBox.setTitle(_translate("MainWindow", "Time Domain"))
        self.antiAliasOut_t_checkBox.setText(_translate("MainWindow", "Anti Aliasing Filter"))
        self.sampleHoldOut_t_checkBox.setText(_translate("MainWindow", "Sample && Hold"))
        self.analogSwitchOut_t_checkBox.setText(_translate("MainWindow", "Analog Switch"))
        self.inputSignalOut_t_checkBox.setText(_translate("MainWindow", "Input Signal"))
        self.recovFilterOut_t_checkBox.setText(_translate("MainWindow", "Recovery Filter"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Frequency Domain"))
        self.antiAliasOut_f_checkBox.setText(_translate("MainWindow", "Anti Aliasing Filter"))
        self.sampleHoldOut_f_checkBox.setText(_translate("MainWindow", "Sample && Hold"))
        self.analogSwitchOut_f_checkBox.setText(_translate("MainWindow", "Analog Switch"))
        self.inputSignalOut_f_checkBox.setText(_translate("MainWindow", "Input Signal"))
        self.recovFilterOut_f_checkBox.setText(_translate("MainWindow", "Recovery Filter"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sampling"))
        self.label.setText(_translate("MainWindow", "Sample Rate (Hz)"))
        self.label_2.setText(_translate("MainWindow", "Sample Cycle"))
        self.updateSampe_pushButton.setText(_translate("MainWindow", "Update Sampling Settings"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Input Signal"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Waveform"))
        self.squareWaveform_radioButton.setText(_translate("MainWindow", "Square"))
        self.altSinWaveform_RadioButton.setText(_translate("MainWindow", "3/2 Sin"))
        self.sinWave_radioButton.setText(_translate("MainWindow", "Sin"))
        self.XcWaveform_radioButton.setText(_translate("MainWindow", "Xc"))
        self.label_3.setText(_translate("MainWindow", "Input Signal Frequency (Hz)"))
        self.label_4.setText(_translate("MainWindow", "Input Signal Amplitude (V)"))
        self.updateInput_pushButton.setText(_translate("MainWindow", "Update Input Signal"))
        self.exportPlots_pushButton.setText(_translate("MainWindow", "Export Plots"))
        self.actionConfig_AAF_Settings.setText(_translate("MainWindow", "AAF Settings"))
        self.actionRecovery_Filter_Settings.setText(_translate("MainWindow", "Recovery Filter Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
